coment bugs v2

diff --git a/.github/workflows/bucket-upload.yaml b/.github/workflows/bucket-upload.yaml
--- a/.github/workflows/bucket-upload.yaml
+++ b/.github/workflows/bucket-upload.yaml
@@ -54,38 +54,43 @@ jobs:
             echo "repos=$REPOS_LIST_CSV" >> $GITHUB_ENV
 
 
-      - name: Run 2ms Scan for each repo
-        run: |
-          mkdir -p $GITHUB_WORKSPACE/results
-      
-          # Dividir a variável 'repos' em uma lista separada por vírgulas
-          IFS=',' read -r -a REPOS_ARRAY <<< "$REPOS_LIST"
-          
-          # Iterar sobre os repositórios no array
-          for repo_url in "${REPOS_ARRAY[@]}"; do
-            repo_name=$(basename "$repo_url" .git)
-            echo "Cloning repository: $repo_url"
-            
-            # Clonar o repositório
-            git clone "$repo_url" "$GITHUB_WORKSPACE/$repo_name"
-            
-            # Verificar se o repositório foi clonado corretamente
-            ls -la "$GITHUB_WORKSPACE/$repo_name"
-
-            ls -la /tmp/2ms/dist/
-
-            
-            # Rodar o 2ms scan no repositório clonado
-            echo "Running 2ms scan on $repo_name"
-            /tmp/2ms/dist/2ms filesystem --path "$GITHUB_WORKSPACE/$repo_name" --ignore-on-exit results --report-path "$GITHUB_WORKSPACE/results/$repo_name.sarif"
-            
-            # Verificar se o comando 2ms foi executado
-            if [ $? -ne 0 ]; then
-              echo "2ms scan failed for $repo_name"
-              exit 1
-            fi
-          done
-      
+            - name: Run 2ms Scan for each repo
+            run: |
+              mkdir -p $GITHUB_WORKSPACE/results
+    
+              IFS=',' read -r -a REPOS_ARRAY <<< "$REPOS_LIST"
+    
+              # Verificar se o binário 2ms existe
+              if [ ! -f /tmp/2ms/dist/2ms ]; then
+                echo "2ms binary not found!"
+                exit 1
+              fi
+    
+              for repo_url in "${REPOS_ARRAY[@]}"; do
+                repo_name=$(basename "$repo_url" .git)
+                echo "Cloning repository: $repo_url"
+                
+                # Clonar o repositório
+                git clone "$repo_url" "$GITHUB_WORKSPACE/$repo_name"
+                
+                # Verificar se o repositório foi clonado corretamente
+                ls -la "$GITHUB_WORKSPACE/$repo_name"
+                
+                # Verificar se o binário 2ms existe
+                ls -la /tmp/2ms/dist/
+    
+                echo "Running 2ms scan on $repo_name"
+                
+                # Executar o scan com 2ms
+                /tmp/2ms/dist/2ms filesystem --path "$GITHUB_WORKSPACE/$repo_name" --ignore-on-exit results --report-path "$GITHUB_WORKSPACE/results/$repo_name.sarif"
+                
+                # Verificar se o comando 2ms foi executado corretamente
+                if [ $? -ne 0 ]; then
+                  echo "2ms scan failed for $repo_name, continuing with the next repo."
+                  continue
+                fi
+              done
+              
       - name: Get Results Directory
         id: get_results_dir
         run: |
