exit 1

diff --git a/.github/workflows/validate-readme.yml b/.github/workflows/validate-readme.yml
--- a/.github/workflows/validate-readme.yml
+++ b/.github/workflows/validate-readme.yml
@@ -20,5 +20,6 @@ jobs:
       - name: validate README wasn't updated
         run: |
           if ! git diff-index --quiet HEAD; then
-            echo "::error:: file=README.md,title=Outdated README::README.md is outdated, please run ./.ci/update-readme.sh"
+            echo "::error file=README.md,title=Outdated README::README.md is outdated, please run ./.ci/update-readme.sh"
+            exit 1
           fi
